language: cpp
os: osx

osx_image:
- xcode9.4
- xcode10.3
- xcode11.3
- xcode6.4
- xcode8
- xcode9.2

install: 
- "wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh"
- "bash ~/miniconda.sh -b -p $HOME/miniconda"
- "git clone --recurse-submodules --branch master --single-branch https://github.com/CICE-Consortium/CICE.git $HOME/cice"

script:
- "cd $HOME && mkdir -p cice-dirs/runs cice-dirs/baseline cice-dirs/input"
- "source $HOME/miniconda/bin/activate"
- "conda init"
- "cd $HOME/cice"
- "conda env create -f configuration/scripts/machines/environment.yml"
- "./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case1"
- "cd ~/cice-dirs/cases/case1 && ./cice.build"
- "cd ~/cice-dirs/cases/case1 && ./cice.run"
