name: Catalina
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: "conda-env Catalina"
    # This job runs on macOS 10.15 Catalina
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: system info
        run: |
          which wget
          which curl
          python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $(which csh)
          csh -v
          uname -a
          sw_vers
      - name : install conda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
      - name: clone CICE
        run: |
          git clone --recurse-submodules --branch conda-env --single-branch https://github.com/phil-blain/CICE.git $HOME/cice
      - name: setup conda env
        run: |
          cd $HOME && mkdir -p cice-dirs/runs cice-dirs/baseline cice-dirs/input
          source $HOME/miniconda/bin/activate
          conda init zsh
          cd $HOME/cice
          conda env create -f configuration/scripts/machines/environment.yml
      - name: check conda env
        run: |
          zsh -c 'source $HOME/.zshrc && conda activate cice && which clang && which gfortran && which mpifort && which mpicc && which make'
      - name: compile CICE
        run: |
          cd $HOME/cice
          ./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case1
          cd ~/cice-dirs/cases/case1
          zsh -c 'source $HOME/.zshrc && which clang && which gfortran && ./cice.build'
