name: Catalina
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: "conda-env Catalina"
    # This job runs on macOS 10.15 Catalina
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: build and run hello world openmp fortran - homebrew gfortran
        run: |
          gfortran-10 -fopenmp omp.f -o omp
          OMP_NUM_THREAD=2 ./omp
      - name: reset toolchain to commandlinetools
        run: |
          sudo xcode-select -r
          sudo xcode-select -s /Library/Developer/CommandLineTools
      - name: system info
        run: |
          type wget
          type curl
          type csh
          echo "readlink \$(which csh): $(python -c 'import os, sys; print os.path.realpath(sys.argv[1])' $(which csh))"
          echo "csh --version: $(csh --version)"
          echo "uname -a: $(uname -a)"
          echo "sw_vers: $(sw_vers)"
          echo "xcrun --show-sdk-path: $(xcrun --show-sdk-path)"
          echo "xcode-select -p: $(xcode-select -p)"
      - name : install miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O ~/miniconda.sh
          bash ~/miniconda.sh -b -p $HOME/miniconda
      - name: clone CICE
        run: |
          git clone --recurse-submodules --single-branch --depth=1 --shallow-submodules https://github.com/CICE-Consortium/CICE.git $HOME/cice
      - name: setup "cice" conda env
        run: |
          cd $HOME && mkdir -p cice-dirs/runs cice-dirs/baseline cice-dirs/input
          source $HOME/miniconda/bin/activate
          conda init zsh
          conda init tcsh
          cd $HOME/cice
          conda env create -f configuration/scripts/machines/environment.yml
      - name: check conda env (zsh)
        shell: /bin/zsh -i -e {0}
        run: |
          conda activate cice && type clang && type gfortran && type mpifort && type mpicc && type make
          cat $HOME/miniconda/envs/cice/etc/conda/activate.d/activate_clang_osx-64.sh
      - name: check conda env (csh)
        shell: /bin/csh {0}
        run: |
          conda activate cice && type clang && type gfortran && type mpifort && type mpicc && type make
      - name: build and run hello world openmp fortran - conda-forge gfortran
        run: |
          zsh -c 'source $HOME/.zshrc && gfortran -fopenmp omp.f -o omp'
          OMP_NUM_THREAD=2 ./omp
      - name: compile CICE (zsh) - serial (1x1)
        run: |
          cd $HOME/cice
          ./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case1 -p 1x1
          cd ~/cice-dirs/cases/case1
          zsh -c 'source $HOME/.zshrc && ./cice.build'
      - name: compile CICE (zsh) - MPI only (4x1)
        run: |
          cd $HOME/cice
          ./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case2 -p 4x1
          cd ~/cice-dirs/cases/case2
          zsh -c 'source $HOME/.zshrc && ./cice.build'
      - name: compile CICE (zsh) - MPI+OpenMP (2x2)
        run: |
          cd $HOME/cice
          ./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case3 -p 2x2
          cd ~/cice-dirs/cases/case3
          zsh -c 'source $HOME/.zshrc && ./cice.build'
      - name: compile CICE (zsh) - OpenMP only (1x2)
        run: |
          cd $HOME/cice
          ./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case4 -p 1x2
          cd ~/cice-dirs/cases/case4
          zsh -c 'source $HOME/.zshrc && ./cice.build'
      - name: compile CICE (csh)
        run: |
          cd $HOME/cice
          ./cice.setup -m conda -e macos -c ~/cice-dirs/cases/case5
          cd ~/cice-dirs/cases/case5
          csh -c 'source $HOME/.tcshrc && ./cice.build'
      - name: download input data
        run: |
          wget ftp://ftp.cgd.ucar.edu/archive/Model-Data/CICE/CICE_data_ic_grid.tar.gz && tar xvfz CICE_data_ic_grid.tar.gz -C ~
          wget ftp://ftp.cgd.ucar.edu/archive/Model-Data/CICE/CICE_data_forcing_gx3_all.tar.gz && tar xvfz CICE_data_forcing_gx3_all.tar.gz -C ~
      - name: run CICE (zsh) - serial (1x1)
        run: |
          cd ~/cice-dirs/cases/case1
          zsh -c 'source $HOME/.zshrc && ./cice.run'
